project:
  type: website

website:
  title: "Notebooks"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - twotiles.qmd
      - lise.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
